### ISSUE TITLE
Add proper README with summary of usage, etc.

### ISSUE THREAD

**Issue by aantron** [tmattio/dream-livereload#4]
No rush! Just noting it for now.

**Comment by tmattio** [comment]
I just added a README, feel free to close this if it seems complete enough to you 🙂

**Comment by aantron** [comment]
One last request besides the PR. The CI badge in the README is red, and looking at the history, all CI runs have failed. Is the CI easily fixable? If not, would you consider removing the badge?

**Comment by tmattio** [comment]
The CI is fixed now!

For the record, one of the failure was due to the Windows pipeline, which was failing because `dream` depends on `conf-libev`, which is not available on Windows. Does Dream intend to support Windows? In which case I'll create an issue on the repo.

**Comment by aantron** [comment]
`dream` should not depend on `conf-libev` on Windows. See https://github.com/aantron/dream/blob/795f824490513248dc054b660808320e81cf39a2/dream.opam#L55. What are you observing, in more detail?

Dream does intend to support Windows (and more or less already should), but the best way to support Windows will be when Lwt is switched to use libuv through Luv (or we switch to multicore and multicore supports Windows).

**Comment by aantron** [comment]
I'm closing the issue since the README parts are solved, thanks :)

**Comment by tmattio** [comment]
Maybe I misinterpreted the CI error: https://github.com/tmattio/dream-livereload/runs/2970137498?check_suite_focus=true

The error is:

```
 [ERROR] No solution for dream-livereload: The following dependencies couldn't be met:
            - dream-livereload -> dream -> conf-libev
                unmet availability conditions, e.g. os != "win32"
            - dream-livereload -> dream -> bisect_ppx >= 2.5.0 -> ocaml < 4.12
                base of this switch (use `--unlock-base' to force)
            - dream-livereload -> dream -> bisect_ppx >= 2.5.0 -> ocamlformat = 0.16.0 -> ocaml < 4.12
                base of this switch (use `--unlock-base' to force)
```

**Comment by aantron** [comment]
Perhaps I got the syntax of the `win32` constraint wrong. I opened https://github.com/aantron/dream/issues/89 to remind myself to decide to either spend time porting Lwt to Luv, or else make sure the build works with a conditional libev dependency otherwise.

I'm concerned about the Bisect_ppx messages. Bisect_ppx doesn't actually constraint Dream from installing on 4.12. Is this due to ocamlformat? Is there a stale cache in CI?
