### ISSUE TITLE
The `inject_script` middleware mutates the HTML

### ISSUE THREAD

**Issue by tmattio** [tmattio/dream-livereload#5]
I noticed this when trying to use AlpineJS in the HTML. The `:class` attribute will be mutated to `class`, which is then not used by Alpine.

**Comment by tmattio** [comment]
See https://github.com/aantron/lambdasoup/issues/39

**Comment by aantron** [comment]
Should be fixed after https://github.com/ocaml/opam-repository/pull/19001 is merged.

**Comment by tmattio** [comment]
I added a dependency on `markup >= 1.0.2`. Thanks!
