### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by aantron** [tmattio/dream-livereload#8]
- Title the repo either "Dream Live Reload" or "dream-livereload". Obviously the title is arbitrary and the most creative part, so this is the weakest possible suggestion.
- Remove the `.mli` file from the example. IMO it serves as a red herring, especially to beginners that may come to this repo from Dream.

**Comment by tmattio** [comment]
I implemented the suggestions and pushed them in `main`. Thanks a lot!
